from app.models.categoria_docente import CategoriaDocente
from app.models.condicion_laboral import CondicionLaboral
from app.models.resolucion import Resolucion
from app.models.usuario import Usuario
from app.models.docente import Docente
from app.models.docente_resolucion import DocenteResolucion
from app.models.periodo_servicio import PeriodoServicio
from app.models.descuento_periodo import DescuentoPeriodo
from app.models.calculo_tiempo_servicio import CalculoTiempoServicio
from app.models.detalle_calculo import DetalleCalculo